package models

import "time"

// AlertSeverity defines the severity level of an alert
type AlertSeverity string

const (
	SeverityLow      AlertSeverity = "low"
	SeverityMedium   AlertSeverity = "medium"
	SeverityHigh     AlertSeverity = "high"
	SeverityCritical AlertSeverity = "critical"
)

// AlertLog stores every alert generated by the Alert Engine
type AlertLog struct {
	ID             uint          `gorm:"primaryKey;autoIncrement" json:"id"`
	ChangeID       uint          `gorm:"column:change_id;not null;index" json:"change_id"`
	PageID         int           `gorm:"column:page_id;not null;index" json:"page_id"`
	AlertType      string        `gorm:"column:alert_type;type:varchar(50);not null" json:"alert_type"` // price_increase, price_decrease, feature_added, etc.
	Severity       AlertSeverity `gorm:"column:severity;type:varchar(20);not null" json:"severity"`
	Summary        string        `gorm:"column:summary;type:text" json:"summary"`
	Recommendation string        `gorm:"column:recommendation;type:varchar(500)" json:"recommendation"`
	Notified       bool          `gorm:"column:notified;default:false" json:"notified"`
	NotifiedAt     *time.Time    `gorm:"column:notified_at" json:"notified_at"`
	NotifyChannel  string        `gorm:"column:notify_channel;type:varchar(50)" json:"notify_channel"` // email, webhook, log
	CreatedAt      time.Time     `gorm:"column:created_at;autoCreateTime" json:"created_at"`
}

func (AlertLog) TableName() string {
	return "alert_logs"
}
